### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by jirihelmich** [tobice/payola-viz#18] opened 2016-07-19 06:17 UTC
[LP-AppGen_Master_1.log.txt](https://github.com/tobice/LDVMi/files/370756/LP-AppGen_Master_1.log.txt)

**Comment by tobice** [comment] 2016-07-19 08:20
It works smoothly with `sbt dist`. It only breaks when executed using `activator`. I will look into it.

**Comment by tobice** [comment] 2016-07-19 08:31
It should be fixed now. For some reason, activator is way more sensitive to build.sbt file structure (missing or extra blank lines) compared to sbt.

**Closed as completed** 2016-07-19 08:30 UTC

**Comment by jirihelmich** [comment] 2016-07-19 08:32
Yes, the build server picked up the commit and the build is running now.

**Comment by jirihelmich** [comment] 2016-07-19 08:49
It's running, but it throws some flexbox css loading errors in the console. However, the university connection is very slow right now, so it might be that.

http://xrg12.projekty.ms.mff.cuni.cz:58080/appgen

You can try and if you see a problem, just commit into your repo, it should be deployed automatically within 5 minutes after the commit.

**Comment by tobice** [comment] 2016-07-19 09:16
Thank you, this is great. 

The problem is with the JavaScript bundle. For some reason, it is slightly different from the bundle I get when I compile it locally. Any chance I could access the build log? The npm output should be included.

**Comment by jirihelmich** [comment] 2016-07-19 09:41
[LP-AppGen_Master_3.log.txt](https://github.com/tobice/LDVMi/files/371115/LP-AppGen_Master_3.log.txt)

**Comment by jirihelmich** [comment] 2016-07-22 21:15
What's the status? I see the same error. Need help?

**Comment by tobice** [comment] 2016-07-22 21:51
I guess my e-mail got lost somewhere along the way.

The problem is with a rather archaic version of `node` and `npm` on the server. Some of the dependencies complain about it and refuse to compile. Do you think you could look into it?

My local setup (for which it's working) looks like this:

```
tobik@zenbook ~ $ npm --version
2.15.5
tobik@zenbook ~ $ node --version
v4.4.5
```

**Comment by jirihelmich** [comment] 2016-07-22 21:52
Should be an easyfix, just say which version you need.

**Comment by jirihelmich** [comment] 2016-07-22 21:52
Oh, sorry.

**Comment by jirihelmich** [comment] 2016-07-22 21:54
```
helmich@xrg12:~$ npm -v
1.4.14
helmich@xrg12:~$ node -v
v0.10.29
```

Well...

**Comment by jirihelmich** [comment] 2016-07-22 21:56
```
root@xrg12:~# npm -v
3.9.5
root@xrg12:~# node -v
v6.2.2
```

**Comment by jirihelmich** [comment] 2016-07-22 22:02
Not sure it helped, though. The build finished and the problem persists.

**Comment by tobice** [comment] 2016-07-22 22:04
I'm examining the log. It looks good, the errors are gone. Is it possible that the JS file is somewhere cached?

**Comment by tobice** [comment] 2016-07-22 22:05
The log contains this:

```
[23:59:20][Step 1/3] ERROR in The `libsass` binding was not found in /usr/local/teamcity-agents/buildAgent/work/c53d396748485d82/src/node_modules/node-sass/vendor/linux-x64-48/binding.node
[23:59:20][Step 1/3] This usually happens because your node version has changed.
[23:59:20][Step 1/3] Run `npm rebuild node-sass` to build the binding for your current node version.
```

Do you think you could run  `npm rebuild node-sass` for me?

**Comment by jirihelmich** [comment] 2016-07-22 22:06
Done.

**Comment by jirihelmich** [comment] 2016-07-22 22:11
It works.

**Comment by tobice** [comment] 2016-07-22 22:17
Awesome.

Yeah, it was all caused by one annoying dependency which is actually not that important but it is the only one that requires SASS to work. I should have gotten rid of it long time ago.

Anyway, everything seems to be working, feel free to generate applications :) I used my import script so everything is ready and the sample data sources are there.

I'm only afraid that at this moment I will have time to fix only the most pressing issues.

**Comment by jirihelmich** [comment] 2016-07-22 22:20
@jakubklimek, @martinnec: If you want, you can test the appgen as well at http://xrg12.projekty.ms.mff.cuni.cz:58080/appgen.
